import "./globals.css";
import Link from "next/link";
import { House, Search, CollectionPlay, PlusLg, Globe } from "react-bootstrap-icons";
import "../src/css/main-layout.css";
import Navigation from "../pages/components/navigations";
import MobileNavbar from "./mobile";

export const metadata = {
  title: "Melodi Mix - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="home-container">
          <nav id="navbar">
            <Navigation />
            <div id="login-register">
              <Link id="register" href="/register">
                <button>Daftar</button>
              </Link>
              <Link id="login" href="/login">
                <button>Masuk</button>
              </Link>
            </div>
          </nav>

          <MobileNavbar />

          <div id="home-menu">
            <Link href="/">
              <img src="https://i.imgur.com/Sm5pkYP.png" alt="Logo MelodiMix" title="MelodiMix" />
            </Link>
            <Link href="/">
              <div id="home-menu-beranda">
                <House />
                <span>Beranda</span>
              </div>
            </Link>
            <Link href="/search">
              <div id="home-menu-search">
                <Search />
                <span>Cari</span>
              </div>
            </Link>
          </div>

          <div id="home-collection">
            <div id="collection">
              <div id="collection-title">
                <div id="collection-title-logo">
                  <CollectionPlay /> <span title="Lihat koleksi kamu">Koleksi Kamu</span>
                </div>

                <span>
                  <PlusLg id="collection-title-add" title="Tambah koleksi kamu" />
                </span>
              </div>
              <div id="collection-playlist">
                <div id="collection-playlist-music">
                  <h3>Buat Playlist Pertamamu!</h3>
                  <p>Ikuti intruksinya dan nikmati playlistnya!</p>
                  <Link href="/playlist/add">Buat Playlist!</Link>
                </div>
                <div id="collection-playlist-podcast">
                  <h3>Jelajahi podcast kesayangan!</h3>
                  <p>Dengarkan podcast kesayanganmu di sini!</p>
                  <Link href="/podcast/add">Jelajahi Podcast!</Link>
                </div>
              </div>
            </div>
            <div id="collection-language">
              <div id="collection-language-select">
                <Globe /> <span>Bahasa Indonesia</span>
              </div>
            </div>
          </div>

          <div id="home-music">{children}</div>
          <footer id="footer">
            <div id="footer-text">
              <h2>Ayo daftar!</h2>
              <p>Awali hari dengan melodi yang membara dan sudahi hari dengan melodi yang merdu!</p>
            </div>
            <div id="footer-regist">
              <Link href="/register">Daftar Gratis!</Link>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
